# Generated by Django 5.0.1 on 2024-02-01 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_rename_bettery_cap_gas_car_fuel_eff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricCar',
            fields=[
                ('car_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='car.car')),
                ('battery_capacity', models.IntegerField(default=0)),
            ],
            bases=('car.car',),
        ),
        migrations.CreateModel(
            name='GasCar',
            fields=[
                ('car_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='car.car')),
                ('fuel_efficiency', models.IntegerField(default=0)),
            ],
            bases=('car.car',),
        ),
        migrations.RemoveField(
            model_name='gas_car',
            name='car',
        ),
        migrations.DeleteModel(
            name='Electric_Car',
        ),
        migrations.DeleteModel(
            name='Gas_Car',
        ),
    ]
